services:
  db:
    image: postgres:14
    container_name: db
    networks:
      - my_network
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=stud
      - POSTGRES_PASSWORD=stud
      - POSTGRES_DB=archdb
    volumes:
      - postgres-data:/var/lib/postgresql/data

  user-service:
    build:
      context: budgeting-system
      dockerfile: user_service/Dockerfile
    container_name: user_service
    networks:
      - my_network
    ports:
      - "8002:8002"

  income-service:
    build:
      context: budgeting-system
      dockerfile: income_service/Dockerfile
    container_name: income_service
    networks:
      - my_network
    ports:
      - "8003:8003"

networks:
  my_network:
volumes:
  postgres-data: