services:
  db:
    image: postgres:14
    container_name: db
    environment:
      - POSTGRES_USER=stud
      - POSTGRES_PASSWORD=stud
      - POSTGRES_DB=archdb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U stud -d archdb"]
      interval: 5s
      timeout: 5s
      retries: 5

  user-service:
    build:
      context: .
      dockerfile: user_service/Dockerfile
    container_name: user_service
    environment:
      - DATABASE_URL=postgresql://stud:stud@db:5432/archdb
    ports:
      - "8002:8002"
    depends_on:
      db:
        condition: service_healthy

networks:
  my_network:
volumes:
  postgres-data: